# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-05 18:15
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('course_sessions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('paused', 'Paused'), ('dropped', 'Dropped'), ('graduated', 'Graduated')], default='active', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('session_history', models.ManyToManyField(related_name='sessions_taken', to='course_sessions.Session')),
                ('starting_cohort', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='course_sessions.Cohort')),
            ],
        ),
    ]
