# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-06 03:04
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0002_alias_note'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='created_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='alias',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aliases', to='students.Student'),
        ),
        migrations.AlterField(
            model_name='note',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='students.Student'),
        ),
        migrations.AlterField(
            model_name='student',
            name='session_history',
            field=models.ManyToManyField(blank=True, related_name='students', to='course_sessions.Session'),
        ),
    ]
