# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-05 18:15
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('course_sessions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='instructor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='session',
            name='start_date',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='course_sessions.Cohort'),
        ),
        migrations.AddField(
            model_name='course',
            name='parent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='course_sessions.ParentCourse'),
        ),
    ]
