# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-10 00:26
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('course_sessions', '0003_auto_20170705_1328'),
    ]

    operations = [
        migrations.AlterField(
            model_name='session',
            name='instructor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to=settings.AUTH_USER_MODEL),
        ),
    ]
