# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-10 18:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course_sessions', '0004_auto_20170709_1726'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='session',
            name='lecture_link',
        ),
        migrations.AddField(
            model_name='course',
            name='lecture_link',
            field=models.CharField(default='supercoollink.zooom.com', max_length=100),
            preserve_default=False,
        ),
    ]
